os: linux
dist: bionic
language: java
services:
  - docker
  - mysql
jdk: openjdk11
addons:
  hosts:
    - mariadb.example.com

before_install:
  - git clone https://github.com/mariadb-corporation/connector-test-machine.git
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

cache:
  directories:
    - $HOME/docker
    - $HOME/.m2

env: local=0

install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install openjdk11 maven
        export PATH=$(cmd.exe //c "refreshenv > nul & C:\Progra~1\Git\bin\bash -c 'echo \$PATH' ")
        connector-test-machine/launch.bat -t "$srv" -v "$v" -d testj
        ;;
      linux)
        source connector-test-machine/launch.sh -t "$srv" -v "$v" -d testj -n 0 -l "$local" -p "$packet"
        ;;
    esac

jobs:
  allow_failures:
    - env: srv=build
  include:
    - env: srv=mariadb v=10.6
      os: windows
      language: shell
    - env: srv=mariadb v=10.2 local=1
    - env: srv=mariadb v=10.3 local=1
    - env: srv=mariadb v=10.4 local=1
    - env: srv=mariadb v=10.5 local=1
    - env: srv=mariadb v=10.7 local=1
    - env: srv=mariadb v=10.8 local=1
    - env: srv=mariadb v=10.6 packet=40
      jdk: openjdk8
    - env: srv=mariadb v=10.6 packet=40
      jdk: openjdk17
    - env: srv=mariadb v=10.6 packet=8
    - env: srv=mariadb v=10.6 local=1 BENCH=1
    - if: type = push AND fork = false
      env: srv=maxscale
    - if: type = push AND fork = false
      env: srv=build
    - if: type = push AND fork = false
      env: srv=mariadb-es v=10.6
    - if: type = push AND fork = false
      env: srv=mysql v=5.7
    - if: type = push AND fork = false
      env: srv=mysql v=8.0 TEST_DB_OTHER=allowPublicKeyRetrieval
    - if: type = push AND fork = false
      env: srv=skysql
    - if: type = push AND fork = false
      env: srv=skysql-ha


script:
  - mvn clean -Dmaven.test.skip
  - if [ -n "$BENCH" ] ; then mvn package -P bench -Dmaven.test.skip -Dmaven.javadoc.skip=true ; fi
  - if [ -n "$BENCH" ] ; then java -Duser.country=US -Duser.language=en -DTEST_PORT=$TEST_DB_PORT -DTEST_HOST=$TEST_DB_HOST -DTEST_USERNAME=$TEST_DB_USER -DTEST_PASSWORD=$TEST_DB_PASSWORD -jar target/benchmarks.jar; fi
  - if [ -z "$BENCH" ] ; then MAVEN_SKIP_RC=true MAVEN_OPTS="-Xmx2g" mvn clean test -DjobId=${TRAVIS_JOB_ID}; fi

after_script:
  - bash <(curl -s https://codecov.io/bash)
